[[redirects]]
  from = "/mp3/*"
  to = "https://vote-quimby.s3.amazonaws.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
